#apollo相关配置，可以在运行时单独指定
app:
    id: example-server
apollo:
    meta: http://182.92.152.103:7777
    bootstrap:
        enabled: true
        eagerLoad:
            enabled: true
    namespaces: application-server-global,application
